apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpv
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/volumes/data
